### ISSUE TITLE
Verificar a variável de ambiente no Dockerfile

### ISSUE THREAD

**Issue by HenriqueCCdA** [Riverfount/todo-project#18]
Eu acho que é `PYTHONUNBUFFERED` mesmo. 

1. https://medium.com/vantageai/how-to-make-your-python-docker-images-secure-fast-small-b3a6870373a0
2. https://alphacoder.xyz/dockerizing-django/
3. https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED

Não ache ainda nenhuma referência com `PYTHONBUFFERED`

**Comment by Riverfount** [comment]
Vou arrumar no nosso projeto! Obrigado pelas informações e contribuição.
